title: Project
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
    width: 1/2
  author:
    label: Author
    type: text
    width: 1/2
  bgcolor:
    label: Background Color
    type: color
    width: 1/3
  headercolor:
    label: Header Nav color
    type: select
    options:
      light-nav: Light
      dark-nav: Dark
    width: 2/3
  tags:
    label: tags
    type: tags
  description:
    label: Description
    type:  textarea
