title: Project
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
    width: 1/3
  author:
    label: Author
    type: text
    width: 1/3
  bgcolor:
    label: Background Color
    type: color
    width: 1/3
  tags:
    label: tags
    type: tags
  description:
    label: Description
    type:  textarea
